### PR TITLE
Snp0301 readme 1

### PR DESCRIPTION
**Pull request by SNP0301**
I translated almost of README.md first.

Also, I have questions about this markdown's text and messages.

1. What does mean ' besides, don't you feel like a chad _cheating the system_? ' I couldn't find specific meaning of  the word 'chad'.
2. When you say 'You may also try reusing some code for automating something else ^^', does it mean that other user can reuse the code for automating another objects for their own use?

I hope you check the changed texts first and suggestion about theses questions,
and I will fix and append the texts sooner.

thx :)

### CODE REVIEW

**Comment by SNP0301** [comment]
1. Oh I see :) then I think I can bring some smooth Korean internet joke. Of course, I will comment here to explain the joke. 

for sure! I will follow the method what you've mentioned soon!

**Comment by SNP0301** [comment]
Good afternoon :)
Here are what I did below : 
- [x] Make another README (***README.ko.md***)
- [x] Link from ENG to KOR
   - [x] Make eng badge
   - [x] add eng badge on README.ko.md
 
And these are what I couldn't complete because of the **different file path**.
(I guess it should be completed after you **merge this branch** and **create README.ko.md's path** in your main branch)
 - [ ] Link from KOR to ENG
   - [ ] Make kor badge
   - [ ] add kor badge on README.md

**Review by SNP0301 — COMMENTED** [review]
1. Create README.ko.md
2. Add link(from KOR to ENG) on README.ko.md

**Comment by fedebotu** [comment]
Merged
I also put a small reference to Korean in the English README as "한국어판", hope Papago was correct. You can modify it if it sounds weird :)

**Comment by SNP0301** [comment]
Nice 👍 

I will translate other texts soon :)

**Pull request merged**
